# Generated by Django 3.1.4 on 2021-01-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210104_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to=''),
        ),
    ]
