# Generated by Django 3.1.4 on 2021-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210104_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/pic.jpg', null=True, upload_to=None),
        ),
    ]
